export const drinks = [
  {
    idDrink: '11000',
    strDrink: 'Mojito',
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    'strDrinkZH-HANS': null,
    'strDrinkZH-HANT': null,
    strTags: 'IBA,ContemporaryClassic,Alcoholic,USA',
    strVideo: null,
    strCategory: 'Cocktail',
    strIBA: 'Contemporary Classics',
    strAlcoholic: 'Alcoholic',
    strGlass: 'Highball glass',
    strInstructions:
      'Muddle mint leaves with sugar and lime juice. Add a splash of soda water and fill the glass with cracked ice. Pour the rum and top with soda water. Garnish and serve with straw.',
    strInstructionsES: null,
    strInstructionsDE:
      'Minzbl\u00e4tter mit Zucker und Limettensaft verr\u00fchren. F\u00fcge einen Spritzer Sodawasser hinzu und f\u00fclle das Glas mit gebrochenem Eis. Den Rum eingie\u00dfen und mit Sodawasser \u00fcbergie\u00dfen. Garnieren und mit einem Strohhalm servieren.',
    strInstructionsFR: null,
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb:
      'https://www.thecocktaildb.com/images/media/drink/rxtqps1478251029.jpg',
    strIngredient1: 'Light rum',
    strIngredient2: 'Lime',
    strIngredient3: 'Sugar',
    strIngredient4: 'Mint',
    strIngredient5: 'Soda water',
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '2-3 oz ',
    strMeasure2: 'Juice of 1 ',
    strMeasure3: '2 tsp ',
    strMeasure4: '2-4 ',
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2016-11-04 09:17:09',
  },
  {
    idDrink: '11002',
    strDrink: 'Long Island Tea',
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    'strDrinkZH-HANS': null,
    'strDrinkZH-HANT': null,
    strTags: 'Strong,Asia,StrongFlavor,Brunch,Vegetarian',
    strVideo: null,
    strCategory: 'Ordinary Drink',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Highball glass',
    strInstructions:
      'Combine all ingredients (except cola) and pour over ice in a highball glass. Add the splash of cola for color. Decorate with a slice of lemon and serve.',
    strInstructionsES: null,
    strInstructionsDE:
      'Alle Zutaten (au\u00dfer Cola) mischen und in einem Highball-Glas \u00fcber Eis gie\u00dfen. F\u00fcge einen Spritzer Cola hinzu, um Farbe zu erhalten. Mit einer Scheibe Zitrone dekorieren und servieren.',
    strInstructionsFR: null,
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb:
      'https://www.thecocktaildb.com/images/media/drink/ywxwqs1439906072.jpg',
    strIngredient1: 'Vodka',
    strIngredient2: 'Light rum',
    strIngredient3: 'Gin',
    strIngredient4: 'Tequila',
    strIngredient5: 'Lemon',
    strIngredient6: 'Coca-Cola',
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '1/2 oz ',
    strMeasure2: '1/2 oz ',
    strMeasure3: '1/2 oz ',
    strMeasure4: '1/2 oz ',
    strMeasure5: 'Juice of 1/2 ',
    strMeasure6: '1 splash ',
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2015-08-18 14:54:32',
  },
  {
    idDrink: '11005',
    strDrink: 'Dry Martini',
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    'strDrinkZH-HANS': null,
    'strDrinkZH-HANT': null,
    strTags: 'IBA,Classic',
    strVideo: null,
    strCategory: 'Cocktail',
    strIBA: 'Unforgettables',
    strAlcoholic: 'Alcoholic',
    strGlass: 'Cocktail glass',
    strInstructions:
      'Straight: Pour all ingredients into mixing glass with ice cubes. Stir well. Strain in chilled martini cocktail glass. Squeeze oil from lemon peel onto the drink, or garnish with olive.',
    strInstructionsES: null,
    strInstructionsDE: null,
    strInstructionsFR: null,
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb:
      'https://www.thecocktaildb.com/images/media/drink/9uqt9p1576519019.jpg',
    strIngredient1: 'Gin',
    strIngredient2: 'Dry Vermouth',
    strIngredient3: 'Olive',
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '1 2/3 oz ',
    strMeasure2: '1/3 oz ',
    strMeasure3: '1 ',
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2017-09-02 12:51:35',
  },
  {
    idDrink: '11006',
    strDrink: 'Daiquiri',
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    'strDrinkZH-HANS': null,
    'strDrinkZH-HANT': null,
    strTags: 'IBA,Classic,Beach',
    strVideo: null,
    strCategory: 'Ordinary Drink',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Cocktail glass',
    strInstructions:
      'Pour all ingredients into shaker with ice cubes. Shake well. Strain in chilled cocktail glass.',
    strInstructionsES: null,
    strInstructionsDE:
      'Alle Zutaten in den Shaker mit Eisw\u00fcrfel geben. Gut sch\u00fctteln. In einem gek\u00fchlten Cocktailglas abseihen.',
    strInstructionsFR: null,
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb:
      'https://www.thecocktaildb.com/images/media/drink/usuuur1439906797.jpg',
    strIngredient1: 'Light rum',
    strIngredient2: 'Lime',
    strIngredient3: 'Powdered sugar',
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '1 1/2 oz ',
    strMeasure2: 'Juice of 1/2 ',
    strMeasure3: '1 tsp ',
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2015-08-18 15:06:37',
  },
  {
    idDrink: '11007',
    strDrink: 'Margarita',
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    'strDrinkZH-HANS': null,
    'strDrinkZH-HANT': null,
    strTags: 'IBA,ContemporaryClassic',
    strVideo: null,
    strCategory: 'Ordinary Drink',
    strIBA: 'Contemporary Classics',
    strAlcoholic: 'Alcoholic',
    strGlass: 'Cocktail glass',
    strInstructions:
      'Rub the rim of the glass with the lime slice to make the salt stick to it. Take care to moisten only the outer rim and sprinkle the salt on it. The salt should present to the lips of the imbiber and never mix into the cocktail. Shake the other ingredients with ice, then carefully pour into the glass.',
    strInstructionsES: null,
    strInstructionsDE:
      'Reiben Sie den Rand des Glases mit der Limettenscheibe, damit das Salz daran haftet. Achten Sie darauf, dass nur der \u00e4u\u00dfere Rand angefeuchtet wird und streuen Sie das Salz darauf. Das Salz sollte sich auf den Lippen des Genie\u00dfers befinden und niemals in den Cocktail einmischen. Die anderen Zutaten mit Eis sch\u00fctteln und vorsichtig in das Glas geben.',
    strInstructionsFR: null,
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb:
      'https://www.thecocktaildb.com/images/media/drink/wpxpvu1439905379.jpg',
    strIngredient1: 'Tequila',
    strIngredient2: 'Triple sec',
    strIngredient3: 'Lime juice',
    strIngredient4: 'Salt',
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '1 1/2 oz ',
    strMeasure2: '1/2 oz ',
    strMeasure3: '1 oz ',
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2015-08-18 14:42:59',
  },
  {
    idDrink: '11027',
    strDrink: 'Amaretto Rose',
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    'strDrinkZH-HANS': null,
    'strDrinkZH-HANT': null,
    strTags: null,
    strVideo: null,
    strCategory: 'Ordinary Drink',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Collins glass',
    strInstructions:
      'Pour amaretto and lime juice over ice in a collins glass. Fill with club soda and serve.',
    strInstructionsES: null,
    strInstructionsDE:
      'Amaretto und Limettensaft in einem Collins Glas \u00fcber Eis gie\u00dfen. Mit Soda auff\u00fcllen und servieren.',
    strInstructionsFR: null,
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb:
      'https://www.thecocktaildb.com/images/media/drink/3jm41q1493069578.jpg',
    strIngredient1: 'Amaretto',
    strIngredient2: 'Lime juice',
    strIngredient3: 'Club soda',
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '1 1/2 oz ',
    strMeasure2: '1/2 oz ',
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2017-04-24 22:32:59',
  },
  {
    idDrink: '11117',
    strDrink: 'Blue Lagoon',
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    'strDrinkZH-HANS': null,
    'strDrinkZH-HANT': null,
    strTags: null,
    strVideo: null,
    strCategory: 'Ordinary Drink',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Highball glass',
    strInstructions:
      'Pour vodka and curacao over ice in a highball glass. Fill with lemonade, top with the cherry, and serve.',
    strInstructionsES: null,
    strInstructionsDE:
      'Gie\u00dfen Sie Wodka und Curacao in einem Highball-Glas \u00fcber Eis. Mit Limonade f\u00fcllen, mit der Kirsche verzieren und servieren.',
    strInstructionsFR: null,
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb:
      'https://www.thecocktaildb.com/images/media/drink/vak0e51504389504.jpg',
    strIngredient1: 'Vodka',
    strIngredient2: 'Blue Curacao',
    strIngredient3: 'Lemonade',
    strIngredient4: 'Cherry',
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '1 oz ',
    strMeasure2: '1 oz ',
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2017-09-02 22:58:25',
  },
  {
    idDrink: '11202',
    strDrink: 'Caipirinha',
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    'strDrinkZH-HANS': null,
    'strDrinkZH-HANT': null,
    strTags: 'ContemporaryClassic,IBA',
    strVideo: null,
    strCategory: 'Ordinary Drink',
    strIBA: 'Contemporary Classics',
    strAlcoholic: 'Alcoholic',
    strGlass: 'Old-fashioned glass',
    strInstructions:
      'Place lime and sugar into old fashioned glass and muddle (mash the two ingredients together using a muddler or a wooden spoon). Fill the glass with ice and add the Cacha\u00e7a.',
    strInstructionsES: null,
    strInstructionsDE:
      'Limette und Zucker in ein old-fashioned Glas geben und vermengen (die beiden Zutaten mit einem Mixer oder einem Holzl\u00f6ffel vermengen). F\u00fcllen Sie das Glas mit Eis und geben Sie den Cacha dazu.',
    strInstructionsFR: null,
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb:
      'https://www.thecocktaildb.com/images/media/drink/xyrppt1469090521.jpg',
    strIngredient1: 'Sugar',
    strIngredient2: 'Lime',
    strIngredient3: 'Cachaca',
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '2 tsp',
    strMeasure2: '1 ',
    strMeasure3: '2 1/2 oz ',
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2016-07-21 09:42:01',
  },
  {
    idDrink: '11288',
    strDrink: 'Cuba Libre',
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    'strDrinkZH-HANS': null,
    'strDrinkZH-HANT': null,
    strTags: 'IBA,ContemporaryClassic',
    strVideo: null,
    strCategory: 'Ordinary Drink',
    strIBA: 'Contemporary Classics',
    strAlcoholic: 'Alcoholic',
    strGlass: 'Highball glass',
    strInstructions:
      'Build all ingredients in a Collins glass filled with ice. Garnish with lime wedge.',
    strInstructionsES: null,
    strInstructionsDE:
      'Geben Sie alle Zutaten in ein mit Eis gef\u00fclltes Collins-Glas. Mit Limettenkeil garnieren.',
    strInstructionsFR: null,
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb:
      'https://www.thecocktaildb.com/images/media/drink/uuxsrr1473201663.jpg',
    strIngredient1: 'Light rum',
    strIngredient2: 'Lime',
    strIngredient3: 'Coca-Cola',
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '2 oz ',
    strMeasure2: 'Juice of 1/2 ',
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2016-09-06 23:41:03',
  },
  {
    idDrink: '11403',
    strDrink: 'Gin And Tonic',
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    'strDrinkZH-HANS': null,
    'strDrinkZH-HANT': null,
    strTags: null,
    strVideo: null,
    strCategory: 'Ordinary Drink',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Highball glass',
    strInstructions:
      'Pour the gin and the tonic water into a highball glass almost filled with ice cubes. Stir well. Garnish with the lime wedge.',
    strInstructionsES: null,
    strInstructionsDE:
      'Gie\u00dfen Sie den Gin und das Tonic Water in ein Highball-Glas, das fast mit Eisw\u00fcrfeln gef\u00fcllt ist. Gut umr\u00fchren. Mit dem Limettenkeil garnieren.',
    strInstructionsFR: null,
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb:
      'https://www.thecocktaildb.com/images/media/drink/wtyxvx1472405831.jpg',
    strIngredient1: 'Gin',
    strIngredient2: 'Tonic water',
    strIngredient3: 'Lime',
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '2 oz ',
    strMeasure2: '5 oz ',
    strMeasure3: '1 ',
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2016-08-28 18:37:11',
  },
  {
    idDrink: '17196',
    strDrink: 'Cosmopolitan',
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    'strDrinkZH-HANS': null,
    'strDrinkZH-HANT': null,
    strTags: 'IBA,ContemporaryClassic',
    strVideo: null,
    strCategory: 'Cocktail',
    strIBA: 'Contemporary Classics',
    strAlcoholic: 'Alcoholic',
    strGlass: 'Cocktail glass',
    strInstructions:
      'Add all ingredients into cocktail shaker filled with ice. Shake well and double strain into large cocktail glass. Garnish with lime wheel.',
    strInstructionsES: null,
    strInstructionsDE:
      'Alle Zutaten in den mit Eis gef\u00fcllten Cocktailshaker geben. Gut sch\u00fctteln und doppelt in ein gro\u00dfes Cocktailglas abseihen. Mit Limettenrad garnieren.',
    strInstructionsFR: null,
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb:
      'https://www.thecocktaildb.com/images/media/drink/kpsajh1504368362.jpg',
    strIngredient1: 'Absolut Citron',
    strIngredient2: 'Lime juice',
    strIngredient3: 'Cointreau',
    strIngredient4: 'Cranberry juice',
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '1 1/4 oz ',
    strMeasure2: '1/4 oz ',
    strMeasure3: '1/4 oz ',
    strMeasure4: '1/4 cup ',
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2017-09-02 17:06:02',
  },
  {
    idDrink: '13837',
    strDrink: 'Kir Royale',
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    'strDrinkZH-HANS': null,
    'strDrinkZH-HANT': null,
    strTags: null,
    strVideo: null,
    strCategory: 'Ordinary Drink',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Champagne Flute',
    strInstructions:
      'Pour Creme de cassis in glass, gently pour champagne on top',
    strInstructionsES: null,
    strInstructionsDE:
      'Creme de Cassis in ein Glas geben, vorsichtig Champagner dar\u00fcber gie\u00dfen.',
    strInstructionsFR: null,
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb:
      'https://www.thecocktaildb.com/images/media/drink/yt9i7n1504370388.jpg',
    strIngredient1: 'Creme de Cassis',
    strIngredient2: 'Champagne',
    strIngredient3: null,
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '1 part ',
    strMeasure2: '5 parts ',
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2017-09-02 17:39:48',
  },
];

export const optionsFiltro = (filtro) => {
  if (filtro === 'Alcóolico') {
    return ['Alcóolico', 'Não Alcóolico'];
  } else if (filtro === 'Categoria') {
    return [
      'Ordinary Drink',
      'Cocktail',
      'Cocoa',
      'Shot',
      'Milk / Float / Shake',
      'Other/Unknown',
      'Coffee / Tea',
      'Homemade Liqueur',
      'Punch / Party Drink',
      'Beer',
      'Soft Drink / Soda',
    ];
  } else if (filtro === 'Copo') {
    return [
      'Highball glass',
      'Cocktail glass',
      'Old-fashioned glass',
      'Collins glass',
    ];
  } else {
    return ['aa', 'bb'];
  }
};
